name: Build
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read # Gives permission to read/write to the repo
  packages: read # Gives permission to read/write nuget packages

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Install .NET to Device
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x.x"

      - name: Clone and Checkout the Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run .NET Restore to reload NuGet Packages
        run: dotnet restore

  build-nuget:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Build Default Framework-Dependent Version (for NuGet)
        shell: bash
        run: dotnet publish -c Release -f net8.0 --no-restore -o bin/Release/net8.0

  pack:
    needs: [setup, build-nuget]
    runs-on: self-hosted
    steps:
      - name: Pack NuGet Packages
        id: pack-nuget
        shell: bash
        run: dotnet pack -c Release --no-restore --no-build 

  build:
    needs: [setup, build-nuget, pack]
    runs-on: self-hosted
    strategy:
      max-parallel: 3
      matrix:
        platforms: ["win-x64"] # "win-x86", "linux-x64", "linux-arm64", "osx-x64", "osx-arm64"
    steps:
      - name: Build for NuGet (Framework Dependent)
        shell: bash
        run: dotnet publish -c Release -r "${{ matrix.platforms }}" --self-contained true --no-restore -o bin/Release/${{ matrix.platforms }}


  names:
    runs-on: self-hosted
    needs: [setup, build, pack]
    outputs:
      packages: ${{ steps.extract-nuget-packages.outputs.PACKAGES}}

    steps:
      - name: Extract Nuget Package Names
        id: extract-nuget-packages
        shell: bash
        run: |
          packageNames=()
          while IFS= read -r file; do
              packageNames+=("$(basename "$file")")
          done < <(find . -type f -name "*.nupkg")

          if [ ${#packageNames[@]} -eq 0 ]; then
              echo "No packages found. Setting empty JSON array."
              packageJson="[]"
          elif [ ${#packageNames[@]} -eq 1 ]; then
              echo "Single Package Detected. Formatting in JSON Manually"
              packageJson="[\"${packageNames[0]}\"]"
          else
              echo "Packing as JSON Array"
              packageJson=$(printf '%s\n' "${packageNames[@]}" | jq -R . | jq -s .)
          fi

          # Ensure proper JSON formatting and escaping
          packageJson=$(echo "$packageJson" | jq -c .)

          echo "JSON : $packageJson"
          echo "PACKAGES=$packageJson" >> "$GITHUB_OUTPUT"

  upload:
    runs-on: self-hosted
    needs: [setup, build, names]
    strategy:
      matrix:
        packages: ${{ fromJson(needs.names.outputs.packages) }}
    steps:
      - name: Upload NuGet packages as build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.packages }}
          path: ./nupkg/${{ matrix.packages }}
          retention-days: 1